package com.arix.pokedex.features.type_effectiveness.presentation

import com.arix.pokedex.features.pokemon_list.domain.model.details.Type
import com.arix.pokedex.features.type_effectiveness.domain.model.DamageMultiplier
import com.arix.pokedex.features.type_effectiveness.domain.model.SelectableType
import com.arix.pokedex.features.type_effectiveness.domain.model.TypeEffectiveness

val mockTypeEffectivenessList = listOf(
    TypeEffectiveness(
        type = SelectableType(type = Type("Normal")),
        typesToMultipliers = mapOf(
            Type("Rock") to DamageMultiplier.HALF,
            Type("Steel") to DamageMultiplier.HALF,
            Type("Ghost") to DamageMultiplier.NO_DAMAGE,
            Type("Normal") to DamageMultiplier.NORMAL,
            Type("Fire") to DamageMultiplier.NORMAL,
            Type("Water") to DamageMultiplier.NORMAL,
            Type("Grass") to DamageMultiplier.NORMAL,
            Type("Electric") to DamageMultiplier.NORMAL,
            Type("Ice") to DamageMultiplier.NORMAL,
            Type("Fighting") to DamageMultiplier.NORMAL,
            Type("Poison") to DamageMultiplier.NORMAL,
            Type("Ground") to DamageMultiplier.NORMAL,
            Type("Flying") to DamageMultiplier.NORMAL,
            Type("Psychic") to DamageMultiplier.NORMAL,
            Type("Bug") to DamageMultiplier.NORMAL,
            Type("Dragon") to DamageMultiplier.NORMAL,
            Type("Dark") to DamageMultiplier.NORMAL,
            Type("Fairy") to DamageMultiplier.NORMAL
        )
    ),
    TypeEffectiveness(
        type = SelectableType(type = Type("Fire")),
        typesToMultipliers = mapOf(
            Type("Grass") to DamageMultiplier.DOUBLE,
            Type("Bug") to DamageMultiplier.DOUBLE,
            Type("Ice") to DamageMultiplier.DOUBLE,
            Type("Steel") to DamageMultiplier.DOUBLE,
            Type("Fire") to DamageMultiplier.HALF,
            Type("Water") to DamageMultiplier.HALF,
            Type("Rock") to DamageMultiplier.HALF,
            Type("Dragon") to DamageMultiplier.HALF,
            Type("Normal") to DamageMultiplier.NORMAL,
            Type("Electric") to DamageMultiplier.NORMAL,
            Type("Fighting") to DamageMultiplier.NORMAL,
            Type("Poison") to DamageMultiplier.NORMAL,
            Type("Ground") to DamageMultiplier.NORMAL,
            Type("Flying") to DamageMultiplier.NORMAL,
            Type("Psychic") to DamageMultiplier.NORMAL,
            Type("Ghost") to DamageMultiplier.NORMAL,
            Type("Dark") to DamageMultiplier.NORMAL,
            Type("Fairy") to DamageMultiplier.NORMAL
        )
    ),
    TypeEffectiveness(
        type = SelectableType(type = Type("Water")),
        typesToMultipliers = mapOf(
            Type("Fire") to DamageMultiplier.DOUBLE,
            Type("Ground") to DamageMultiplier.DOUBLE,
            Type("Rock") to DamageMultiplier.DOUBLE,
            Type("Water") to DamageMultiplier.HALF,
            Type("Grass") to DamageMultiplier.HALF,
            Type("Dragon") to DamageMultiplier.HALF,
            Type("Normal") to DamageMultiplier.NORMAL,
            Type("Electric") to DamageMultiplier.NORMAL,
            Type("Ice") to DamageMultiplier.NORMAL,
            Type("Fighting") to DamageMultiplier.NORMAL,
            Type("Poison") to DamageMultiplier.NORMAL,
            Type("Flying") to DamageMultiplier.NORMAL,
            Type("Psychic") to DamageMultiplier.NORMAL,
            Type("Bug") to DamageMultiplier.NORMAL,
            Type("Ghost") to DamageMultiplier.NORMAL,
            Type("Dark") to DamageMultiplier.NORMAL,
            Type("Steel") to DamageMultiplier.NORMAL,
            Type("Fairy") to DamageMultiplier.NORMAL
        )
    ),
    TypeEffectiveness(
        type = SelectableType(type = Type("Grass")),
        typesToMultipliers = mapOf(
            Type("Water") to DamageMultiplier.DOUBLE,
            Type("Ground") to DamageMultiplier.DOUBLE,
            Type("Rock") to DamageMultiplier.DOUBLE,
            Type("Fire") to DamageMultiplier.HALF,
            Type("Grass") to DamageMultiplier.HALF,
            Type("Poison") to DamageMultiplier.HALF,
            Type("Flying") to DamageMultiplier.HALF,
            Type("Bug") to DamageMultiplier.HALF,
            Type("Dragon") to DamageMultiplier.HALF,
            Type("Steel") to DamageMultiplier.HALF,
            Type("Normal") to DamageMultiplier.NORMAL,
            Type("Electric") to DamageMultiplier.NORMAL,
            Type("Ice") to DamageMultiplier.NORMAL,
            Type("Fighting") to DamageMultiplier.NORMAL,
            Type("Psychic") to DamageMultiplier.NORMAL,
            Type("Ghost") to DamageMultiplier.NORMAL,
            Type("Dark") to DamageMultiplier.NORMAL,
            Type("Fairy") to DamageMultiplier.NORMAL
        )
    ),
    TypeEffectiveness(
        type = SelectableType(type = Type("Electric")),
        typesToMultipliers = mapOf(
            Type("Water") to DamageMultiplier.DOUBLE,
            Type("Flying") to DamageMultiplier.DOUBLE,
            Type("Electric") to DamageMultiplier.HALF,
            Type("Grass") to DamageMultiplier.HALF,
            Type("Dragon") to DamageMultiplier.HALF,
            Type("Ground") to DamageMultiplier.NO_DAMAGE,
            Type("Normal") to DamageMultiplier.NORMAL,
            Type("Fire") to DamageMultiplier.NORMAL,
            Type("Ice") to DamageMultiplier.NORMAL,
            Type("Fighting") to DamageMultiplier.NORMAL,
            Type("Poison") to DamageMultiplier.NORMAL,
            Type("Psychic") to DamageMultiplier.NORMAL,
            Type("Bug") to DamageMultiplier.NORMAL,
            Type("Rock") to DamageMultiplier.NORMAL,
            Type("Ghost") to DamageMultiplier.NORMAL,
            Type("Dark") to DamageMultiplier.NORMAL,
            Type("Steel") to DamageMultiplier.NORMAL,
            Type("Fairy") to DamageMultiplier.NORMAL
        )
    ),
    TypeEffectiveness(
        type = SelectableType(type = Type("Ice")),
        typesToMultipliers = mapOf(
            Type("Grass") to DamageMultiplier.DOUBLE,
            Type("Ground") to DamageMultiplier.DOUBLE,
            Type("Flying") to DamageMultiplier.DOUBLE,
            Type("Dragon") to DamageMultiplier.DOUBLE,
            Type("Fire") to DamageMultiplier.HALF,
            Type("Water") to DamageMultiplier.HALF,
            Type("Ice") to DamageMultiplier.HALF,
            Type("Steel") to DamageMultiplier.HALF,
            Type("Normal") to DamageMultiplier.NORMAL,
            Type("Electric") to DamageMultiplier.NORMAL,
            Type("Fighting") to DamageMultiplier.NORMAL,
            Type("Poison") to DamageMultiplier.NORMAL,
            Type("Psychic") to DamageMultiplier.NORMAL,
            Type("Bug") to DamageMultiplier.NORMAL,
            Type("Rock") to DamageMultiplier.NORMAL,
            Type("Ghost") to DamageMultiplier.NORMAL,
            Type("Dark") to DamageMultiplier.NORMAL,
            Type("Fairy") to DamageMultiplier.NORMAL
        )
    ),
    TypeEffectiveness(
        type = SelectableType(type = Type("Fighting")),
        typesToMultipliers = mapOf(
            Type("Normal") to DamageMultiplier.DOUBLE,
            Type("Ice") to DamageMultiplier.DOUBLE,
            Type("Rock") to DamageMultiplier.DOUBLE,
            Type("Dark") to DamageMultiplier.DOUBLE,
            Type("Steel") to DamageMultiplier.DOUBLE,
            Type("Poison") to DamageMultiplier.HALF,
            Type("Flying") to DamageMultiplier.HALF,
            Type("Psychic") to DamageMultiplier.HALF,
            Type("Bug") to DamageMultiplier.HALF,
            Type("Fairy") to DamageMultiplier.HALF,
            Type("Ghost") to DamageMultiplier.NO_DAMAGE,
            Type("Fire") to DamageMultiplier.NORMAL,
            Type("Water") to DamageMultiplier.NORMAL,
            Type("Electric") to DamageMultiplier.NORMAL,
            Type("Grass") to DamageMultiplier.NORMAL,
            Type("Fighting") to DamageMultiplier.NORMAL,
            Type("Ground") to DamageMultiplier.NORMAL,
            Type("Dragon") to DamageMultiplier.NORMAL
        )
    ),
    TypeEffectiveness(
        type = SelectableType(type = Type("Poison")),
        typesToMultipliers = mapOf(
            Type("Grass") to DamageMultiplier.DOUBLE,
            Type("Fairy") to DamageMultiplier.DOUBLE,
            Type("Poison") to DamageMultiplier.HALF,
            Type("Ground") to DamageMultiplier.HALF,
            Type("Rock") to DamageMultiplier.HALF,
            Type("Ghost") to DamageMultiplier.HALF,
            Type("Steel") to DamageMultiplier.NO_DAMAGE,
            Type("Normal") to DamageMultiplier.NORMAL,
            Type("Fire") to DamageMultiplier.NORMAL,
            Type("Water") to DamageMultiplier.NORMAL,
            Type("Electric") to DamageMultiplier.NORMAL,
            Type("Ice") to DamageMultiplier.NORMAL,
            Type("Fighting") to DamageMultiplier.NORMAL,
            Type("Flying") to DamageMultiplier.NORMAL,
            Type("Psychic") to DamageMultiplier.NORMAL,
            Type("Bug") to DamageMultiplier.NORMAL,
            Type("Dragon") to DamageMultiplier.NORMAL,
            Type("Dark") to DamageMultiplier.NORMAL
        )
    ),
    TypeEffectiveness(
        type = SelectableType(type = Type("Ground")),
        typesToMultipliers = mapOf(
            Type("Fire") to DamageMultiplier.DOUBLE,
            Type("Electric") to DamageMultiplier.DOUBLE,
            Type("Poison") to DamageMultiplier.DOUBLE,
            Type("Rock") to DamageMultiplier.DOUBLE,
            Type("Steel") to DamageMultiplier.DOUBLE,
            Type("Grass") to DamageMultiplier.HALF,
            Type("Bug") to DamageMultiplier.HALF,
            Type("Flying") to DamageMultiplier.NO_DAMAGE,
            Type("Normal") to DamageMultiplier.NORMAL,
            Type("Water") to DamageMultiplier.NORMAL,
            Type("Ice") to DamageMultiplier.NORMAL,
            Type("Fighting") to DamageMultiplier.NORMAL,
            Type("Ground") to DamageMultiplier.NORMAL,
            Type("Psychic") to DamageMultiplier.NORMAL,
            Type("Ghost") to DamageMultiplier.NORMAL,
            Type("Dragon") to DamageMultiplier.NORMAL,
            Type("Dark") to DamageMultiplier.NORMAL,
            Type("Fairy") to DamageMultiplier.NORMAL
        )
    ),
    TypeEffectiveness(
        type = SelectableType(type = Type("Flying")),
        typesToMultipliers = mapOf(
            Type("Grass") to DamageMultiplier.DOUBLE,
            Type("Fighting") to DamageMultiplier.DOUBLE,
            Type("Bug") to DamageMultiplier.DOUBLE,
            Type("Electric") to DamageMultiplier.HALF,
            Type("Rock") to DamageMultiplier.HALF,
            Type("Steel") to DamageMultiplier.HALF,
            Type("Normal") to DamageMultiplier.NORMAL,
            Type("Fire") to DamageMultiplier.NORMAL,
            Type("Water") to DamageMultiplier.NORMAL,
            Type("Ice") to DamageMultiplier.NORMAL,
            Type("Poison") to DamageMultiplier.NORMAL,
            Type("Ground") to DamageMultiplier.NORMAL,
            Type("Flying") to DamageMultiplier.NORMAL,
            Type("Psychic") to DamageMultiplier.NORMAL,
            Type("Ghost") to DamageMultiplier.NORMAL,
            Type("Dragon") to DamageMultiplier.NORMAL,
            Type("Dark") to DamageMultiplier.NORMAL,
            Type("Fairy") to DamageMultiplier.NORMAL
        )
    ),
    TypeEffectiveness(
        type = SelectableType(type = Type("Psychic")),
        typesToMultipliers = mapOf(
            Type("Fighting") to DamageMultiplier.DOUBLE,
            Type("Poison") to DamageMultiplier.DOUBLE,
            Type("Psychic") to DamageMultiplier.HALF,
            Type("Steel") to DamageMultiplier.HALF,
            Type("Dark") to DamageMultiplier.NO_DAMAGE,
            Type("Normal") to DamageMultiplier.NORMAL,
            Type("Fire") to DamageMultiplier.NORMAL,
            Type("Water") to DamageMultiplier.NORMAL,
            Type("Electric") to DamageMultiplier.NORMAL,
            Type("Grass") to DamageMultiplier.NORMAL,
            Type("Ice") to DamageMultiplier.NORMAL,
            Type("Ground") to DamageMultiplier.NORMAL,
            Type("Flying") to DamageMultiplier.NORMAL,
            Type("Bug") to DamageMultiplier.NORMAL,
            Type("Rock") to DamageMultiplier.NORMAL,
            Type("Ghost") to DamageMultiplier.NORMAL,
            Type("Dragon") to DamageMultiplier.NORMAL,
            Type("Fairy") to DamageMultiplier.NORMAL
        )
    ),
    TypeEffectiveness(
        type = SelectableType(type = Type("Bug")),
        typesToMultipliers = mapOf(
            Type("Grass") to DamageMultiplier.DOUBLE,
            Type("Psychic") to DamageMultiplier.DOUBLE,
            Type("Dark") to DamageMultiplier.DOUBLE,
            Type("Fire") to DamageMultiplier.HALF,
            Type("Fighting") to DamageMultiplier.HALF,
            Type("Poison") to DamageMultiplier.HALF,
            Type("Flying") to DamageMultiplier.HALF,
            Type("Ghost") to DamageMultiplier.HALF,
            Type("Steel") to DamageMultiplier.HALF,
            Type("Fairy") to DamageMultiplier.HALF,
            Type("Normal") to DamageMultiplier.NORMAL,
            Type("Water") to DamageMultiplier.NORMAL,
            Type("Electric") to DamageMultiplier.NORMAL,
            Type("Ice") to DamageMultiplier.NORMAL,
            Type("Ground") to DamageMultiplier.NORMAL,
            Type("Bug") to DamageMultiplier.NORMAL,
            Type("Rock") to DamageMultiplier.NORMAL,
            Type("Dragon") to DamageMultiplier.NORMAL
        )
    ),
    TypeEffectiveness(
        type = SelectableType(type = Type("Rock")),
        typesToMultipliers = mapOf(
            Type("Fire") to DamageMultiplier.DOUBLE,
            Type("Ice") to DamageMultiplier.DOUBLE,
            Type("Flying") to DamageMultiplier.DOUBLE,
            Type("Bug") to DamageMultiplier.DOUBLE,
            Type("Fighting") to DamageMultiplier.HALF,
            Type("Ground") to DamageMultiplier.HALF,
            Type("Steel") to DamageMultiplier.HALF,
            Type("Normal") to DamageMultiplier.NORMAL,
            Type("Water") to DamageMultiplier.NORMAL,
            Type("Electric") to DamageMultiplier.NORMAL,
            Type("Grass") to DamageMultiplier.NORMAL,
            Type("Poison") to DamageMultiplier.NORMAL,
            Type("Psychic") to DamageMultiplier.NORMAL,
            Type("Rock") to DamageMultiplier.NORMAL,
            Type("Ghost") to DamageMultiplier.NORMAL,
            Type("Dragon") to DamageMultiplier.NORMAL,
            Type("Dark") to DamageMultiplier.NORMAL,
            Type("Fairy") to DamageMultiplier.NORMAL
        )
    ),
    TypeEffectiveness(
        type = SelectableType(type = Type("Ghost")),
        typesToMultipliers = mapOf(
            Type("Psychic") to DamageMultiplier.DOUBLE,
            Type("Ghost") to DamageMultiplier.DOUBLE,
            Type("Dark") to DamageMultiplier.HALF,
            Type("Normal") to DamageMultiplier.NO_DAMAGE,
            Type("Fire") to DamageMultiplier.NORMAL,
            Type("Water") to DamageMultiplier.NORMAL,
            Type("Electric") to DamageMultiplier.NORMAL,
            Type("Grass") to DamageMultiplier.NORMAL,
            Type("Ice") to DamageMultiplier.NORMAL,
            Type("Fighting") to DamageMultiplier.NORMAL,
            Type("Poison") to DamageMultiplier.NORMAL,
            Type("Ground") to DamageMultiplier.NORMAL,
            Type("Flying") to DamageMultiplier.NORMAL,
            Type("Bug") to DamageMultiplier.NORMAL,
            Type("Rock") to DamageMultiplier.NORMAL,
            Type("Dragon") to DamageMultiplier.NORMAL,
            Type("Steel") to DamageMultiplier.NORMAL,
            Type("Fairy") to DamageMultiplier.NORMAL
        )
    ),
    TypeEffectiveness(
        type = SelectableType(type = Type("Dragon")),
        typesToMultipliers = mapOf(
            Type("Dragon") to DamageMultiplier.DOUBLE,
            Type("Steel") to DamageMultiplier.HALF,
            Type("Fairy") to DamageMultiplier.NO_DAMAGE,
            Type("Normal") to DamageMultiplier.NORMAL,
            Type("Fire") to DamageMultiplier.NORMAL,
            Type("Water") to DamageMultiplier.NORMAL,
            Type("Electric") to DamageMultiplier.NORMAL,
            Type("Grass") to DamageMultiplier.NORMAL,
            Type("Ice") to DamageMultiplier.NORMAL,
            Type("Fighting") to DamageMultiplier.NORMAL,
            Type("Poison") to DamageMultiplier.NORMAL,
            Type("Ground") to DamageMultiplier.NORMAL,
            Type("Flying") to DamageMultiplier.NORMAL,
            Type("Psychic") to DamageMultiplier.NORMAL,
            Type("Bug") to DamageMultiplier.NORMAL,
            Type("Rock") to DamageMultiplier.NORMAL,
            Type("Ghost") to DamageMultiplier.NORMAL,
            Type("Dark") to DamageMultiplier.NORMAL
        )
    ),
    TypeEffectiveness(
        type = SelectableType(type = Type("Dark")),
        typesToMultipliers = mapOf(
            Type("Psychic") to DamageMultiplier.DOUBLE,
            Type("Ghost") to DamageMultiplier.DOUBLE,
            Type("Fighting") to DamageMultiplier.HALF,
            Type("Dark") to DamageMultiplier.HALF,
            Type("Fairy") to DamageMultiplier.HALF,
            Type("Normal") to DamageMultiplier.NORMAL,
            Type("Fire") to DamageMultiplier.NORMAL,
            Type("Water") to DamageMultiplier.NORMAL,
            Type("Electric") to DamageMultiplier.NORMAL,
            Type("Grass") to DamageMultiplier.NORMAL,
            Type("Ice") to DamageMultiplier.NORMAL,
            Type("Poison") to DamageMultiplier.NORMAL,
            Type("Ground") to DamageMultiplier.NORMAL,
            Type("Flying") to DamageMultiplier.NORMAL,
            Type("Bug") to DamageMultiplier.NORMAL,
            Type("Rock") to DamageMultiplier.NORMAL,
            Type("Dragon") to DamageMultiplier.NORMAL,
            Type("Steel") to DamageMultiplier.NORMAL
        )
    ),
    TypeEffectiveness(
        type = SelectableType(type = Type("Steel")),
        typesToMultipliers = mapOf(
            Type("Ice") to DamageMultiplier.DOUBLE,
            Type("Rock") to DamageMultiplier.DOUBLE,
            Type("Fairy") to DamageMultiplier.DOUBLE,
            Type("Fire") to DamageMultiplier.HALF,
            Type("Water") to DamageMultiplier.HALF,
            Type("Electric") to DamageMultiplier.HALF,
            Type("Steel") to DamageMultiplier.HALF,
            Type("Normal") to DamageMultiplier.NORMAL,
            Type("Grass") to DamageMultiplier.NORMAL,
            Type("Fighting") to DamageMultiplier.NORMAL,
            Type("Poison") to DamageMultiplier.NORMAL,
            Type("Ground") to DamageMultiplier.NORMAL,
            Type("Flying") to DamageMultiplier.NORMAL,
            Type("Psychic") to DamageMultiplier.NORMAL,
            Type("Bug") to DamageMultiplier.NORMAL,
            Type("Ghost") to DamageMultiplier.NORMAL,
            Type("Dragon") to DamageMultiplier.NORMAL,
            Type("Dark") to DamageMultiplier.NORMAL
        )
    ),
    TypeEffectiveness(
        type = SelectableType(type = Type("Fairy")),
        typesToMultipliers = mapOf(
            Type("Fighting") to DamageMultiplier.DOUBLE,
            Type("Dragon") to DamageMultiplier.DOUBLE,
            Type("Dark") to DamageMultiplier.DOUBLE,
            Type("Fire") to DamageMultiplier.HALF,
            Type("Poison") to DamageMultiplier.HALF,
            Type("Steel") to DamageMultiplier.HALF,
            Type("Normal") to DamageMultiplier.NORMAL,
            Type("Water") to DamageMultiplier.NORMAL,
            Type("Electric") to DamageMultiplier.NORMAL,
            Type("Grass") to DamageMultiplier.NORMAL,
            Type("Ice") to DamageMultiplier.NORMAL,
            Type("Ground") to DamageMultiplier.NORMAL,
            Type("Flying") to DamageMultiplier.NORMAL,
            Type("Psychic") to DamageMultiplier.NORMAL,
            Type("Bug") to DamageMultiplier.NORMAL,
            Type("Rock") to DamageMultiplier.NORMAL,
            Type("Ghost") to DamageMultiplier.NORMAL,
            Type("Fairy") to DamageMultiplier.NORMAL
        )
    )
)